#!/usr/bin/env bats
# test/compose_overlay_render.bats — compose render assertions for dual-mode overlays
#
# Validates YAML correctness by running `docker compose config` (no daemon needed,
# config-only read) against the base + mode overlay combinations.
#
# Design §7c: render tests are negative/positive assertions over the resolved YAML.
# - contain render: docker.sock ABSENT, network_mode: host ABSENT, internal: true ABSENT
# - dood render: docker.sock PRESENT, network_mode: host PRESENT
# - hardening composes cleanly with both modes
#
# Each test provides dummy non-empty env vars so compose interpolation succeeds without
# a daemon (compose config is offline, doesn't check bind-source path existence).

load "helpers/load"

setup() {
	# Skip entire file if docker is not available.
	if ! command -v docker >/dev/null 2>&1; then
		skip "docker not available"
	fi

	# Dummy env vars required by docker-compose.yml :? guards.
	# Compose config is offline — dummy paths work; no daemon or real fs checks.
	export USER_NAME="testuser"
	export USER_UID="1000"
	export USER_GID="1000"
	export HOST_DOCKER_GID="999"
	export PROJECT_DIR="/tmp/render-test-project"
	export PROJECT_NAME="testproject"
	export DRYDOCK_DISCRIMINATOR="abcd"
	export DRYDOCK_SESSION_CLAUDE_DIR="/tmp/render-cdir"
	export DRYDOCK_SESSION_CLAUDE_JSON="/tmp/render-cjson"
	export DRYDOCK_SESSION_HOOKS_DIR="/tmp/render-hooks"
	export DRYDOCK_TMPFS_SIZE="1g"

	# Phase 2 egress jail: docker-compose.contain.yml references these via :? guards
	# (DRYDOCK_SIDECAR_NAME for the sidecar container_name / HTTPS_PROXY / NO_PROXY,
	# DRYDOCK_EGRESS_FILTER_FILE for the RO filter mount). Without them every contain
	# render aborts. Real values are generated by export_compose_env; for offline
	# render the dummies just need to be non-empty and deterministic.
	export DRYDOCK_SIDECAR_NAME="drydock-testproject-abcd-egress"
	export DRYDOCK_EGRESS_FILTER_FILE="/tmp/render-egress-filter"

	# Clear any ambient mode env vars so tests control the mode explicitly.
	unset DRYDOCK_DOOD DRYDOCK_CONTAIN DRYDOCK_NO_HARDENING

	DRYDOCK_HOME="${DRYDOCK_HOME:-$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)}"
}

# _service_block <service-name> — read rendered `docker compose config` output on
# stdin and print only the block for one service (from "  <name>:" up to the next
# top-level service key at the same 2-space indent). Lets a test scope an assertion
# to one service so a token present elsewhere (e.g. the agent's cap_add) cannot make
# a sidecar-scoped assertion vacuously pass.
_service_block() {
	awk -v svc="  $1:" '
		$0 == svc { inblk = 1; print; next }
		inblk && /^  [^[:space:]]/ { inblk = 0 }
		inblk { print }
	'
}

# ── Contained mode render assertions ─────────────────────────────────────────

@test "render: contain — docker.sock absent" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" != *"docker.sock"* ]]
}

@test "render: contain — network_mode: host absent" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" != *"network_mode: host"* ]]
}

@test "render: contain — internal: true PRESENT on drydock_internal (egress-jail seal)" {
	# Phase 2 INVERTS the Phase 1 egress-open guard (R9.1/R9.2). internal: true on the
	# agent's sole network removes the gateway/NAT path; egress is forced through the
	# proxy sidecar's allowlist. FIRST FAILING TEST: the Phase 1 contain.yml has no
	# internal: true, so this fails until the Phase 2 overlay lands (TDD red→green).
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" == *"internal: true"* ]]
}

@test "render: contain — drydock_net absent (renamed to drydock_internal/drydock_egress)" {
	# Phase 2 renames the single Phase 1 bridge. drydock_net must no longer appear —
	# guards against a half-applied rename leaving a dangling reference.
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" != *"drydock_net"* ]]
}

@test "render: contain — agent attached to drydock_internal (sole network)" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	local _block
	_block="$(printf '%s\n' "$output" | _service_block drydock)"
	[[ "$_block" == *"drydock_internal"* ]]
	[[ "$_block" != *"drydock_egress"* ]]
}

@test "render: contain — network drydock_internal named drydock_internal (fixed, not namespaced)" {
	# Network-leak regression guard (R2.1/R2.3/R9.10), mirrors the Phase 1 drydock_net
	# fixed-name test. Without an explicit name:, Compose namespaces the network as
	# <COMPOSE_PROJECT_NAME>_drydock_internal; drydock's teardown is always
	# `docker rm -f` (never `compose down`), so every session would leak one network
	# and exhaust Docker's ~31-bridge pool. COMPOSE_PROJECT_NAME is set so the
	# namespaced negative is deterministic, not vacuous.
	export COMPOSE_PROJECT_NAME="drydock-testproj-zzzz"
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" == *"name: drydock_internal"* ]]
	[[ "$output" != *"_drydock_internal"* ]]
}

@test "render: contain — network drydock_egress named drydock_egress (fixed, not namespaced)" {
	# Same fixed-name no-leak guard for the external-facing sidecar bridge
	# (R2.2/R2.3/R9.11).
	export COMPOSE_PROJECT_NAME="drydock-testproj-zzzz"
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" == *"name: drydock_egress"* ]]
	[[ "$output" != *"_drydock_egress"* ]]
}

@test "render: contain — drydock-egress sidecar service present (R9.3)" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" == *"drydock-egress:"* ]]
	[[ "$output" == *"image: drydock-egress:latest"* ]]
}

@test "render: contain — sidecar dual-homed to drydock_internal AND drydock_egress (R1-D)" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	local _block
	_block="$(printf '%s\n' "$output" | _service_block drydock-egress)"
	[[ "$_block" == *"drydock_internal"* ]]
	[[ "$_block" == *"drydock_egress"* ]]
}

@test "render: contain — HTTPS_PROXY present on drydock service (R9.4)" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" == *"HTTPS_PROXY"* ]]
	[[ "$output" == *"http://drydock-testproject-abcd-egress:8888"* ]]
}

@test "render: contain — NO_PROXY present on drydock service (loopback + sidecar)" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" == *"NO_PROXY"* ]]
	[[ "$output" == *"127.0.0.1"* ]]
}

@test "render: contain — agent depends_on drydock-egress with service_healthy (R9.6)" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	local _block
	_block="$(printf '%s\n' "$output" | _service_block drydock)"
	[[ "$_block" == *"depends_on"* ]]
	[[ "$_block" == *"drydock-egress"* ]]
	[[ "$_block" == *"service_healthy"* ]]
}

@test "render: contain — effective filter RO-mounted into sidecar (R9.5)" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	local _block
	_block="$(printf '%s\n' "$output" | _service_block drydock-egress)"
	[[ "$_block" == *"/etc/tinyproxy/filter"* ]]
	[[ "$_block" == *"read_only: true"* ]]
}

@test "render: contain — sidecar rootfs read_only: true (A5, service-level not volume-level)" {
	# A5: the sidecar runs with a read-only rootfs. The filter VOLUME also renders
	# read_only: true (at 8-space indent under volumes:), so a block-wide substring
	# match would pass even if the service-level flag were dropped. Scope to the
	# service-level key (exactly 4-space indent) so this catches an A5 regression.
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	local _block
	_block="$(printf '%s\n' "$output" | _service_block drydock-egress)"
	printf '%s\n' "$_block" | grep -qE '^    read_only: true$'
}

@test "render: contain — sidecar tmpfs /run + /tmp (A5, PidFile + runtime dir)" {
	# A5: read_only rootfs requires writable tmpfs for tinyproxy's /run (Debian
	# runtime dir) and /tmp (PidFile). /run is unambiguous (appears only here); the
	# tmpfs /tmp entry is matched as a whole 6-space list line so the filter volume's
	# /tmp/... source path cannot satisfy it vacuously.
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	local _block
	_block="$(printf '%s\n' "$output" | _service_block drydock-egress)"
	printf '%s\n' "$_block" | grep -qE '^    tmpfs:$'
	printf '%s\n' "$_block" | grep -qxE '      - /run'
	printf '%s\n' "$_block" | grep -qxE '      - /tmp'
}

@test "render: contain — sidecar cap_drop present (R9.7, INV-8 hardened)" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	local _block
	_block="$(printf '%s\n' "$output" | _service_block drydock-egress)"
	[[ "$_block" == *"cap_drop"* ]]
	[[ "$_block" == *"ALL"* ]]
}

@test "render: contain — sidecar has NO cap_add (INV-8 zero new caps)" {
	# INV-8 "touched-but-preserved": the sidecar adds zero capabilities. Render WITH
	# hardening so cap_add is present SOMEWHERE (on the agent) — that makes the
	# sidecar-scoped negative meaningful instead of vacuous (the whole render simply
	# lacking cap_add would pass without proving anything).
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		-f "$DRYDOCK_HOME/docker-compose.hardening.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	local _block
	_block="$(printf '%s\n' "$output" | _service_block drydock-egress)"
	[[ "$_block" != *"cap_add"* ]]
}

@test "render: contain — sidecar has healthcheck (R9.8)" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	local _block
	_block="$(printf '%s\n' "$output" | _service_block drydock-egress)"
	[[ "$_block" == *"healthcheck"* ]]
}

@test "render: contain — telemetry env vars present on drydock service (R9.9)" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" == *"DISABLE_TELEMETRY"* ]]
	[[ "$output" == *"DISABLE_ERROR_REPORTING"* ]]
	[[ "$output" == *"CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC"* ]]
}

# ── DooD mode render assertions ───────────────────────────────────────────────

@test "render: dood — docker.sock present" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.dood.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" == *"docker.sock"* ]]
}

@test "render: dood — network_mode: host present" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.dood.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" == *"network_mode: host"* ]]
}

@test "render: dood — internal: true absent (dood unaffected, R9.12)" {
	# Phase 2 regression guard: the egress jail is contained-only. The dood overlay
	# must NEVER gain internal: true (it would break host networking + the socket).
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.dood.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" != *"internal: true"* ]]
}

@test "render: dood — no egress sidecar / proxy / telemetry artifacts (R9.13, R8.2)" {
	# dood must carry none of the Phase 2 egress-jail artifacts: no sidecar service,
	# no HTTPS_PROXY, no allowlist mount, no telemetry-off defaults.
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.dood.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" != *"drydock-egress"* ]]
	[[ "$output" != *"HTTPS_PROXY"* ]]
	[[ "$output" != *"/etc/tinyproxy/filter"* ]]
	[[ "$output" != *"DISABLE_TELEMETRY"* ]]
}

# ── Hardening + mode composition ─────────────────────────────────────────────

@test "render: hardening + contain — cap_drop present, socket absent" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.contain.yml" \
		-f "$DRYDOCK_HOME/docker-compose.hardening.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" == *"cap_drop"* ]]
	[[ "$output" != *"docker.sock"* ]]
}

@test "render: hardening + dood — cap_drop present, socket present" {
	run docker compose \
		-f "$DRYDOCK_HOME/docker-compose.yml" \
		-f "$DRYDOCK_HOME/docker-compose.dood.yml" \
		-f "$DRYDOCK_HOME/docker-compose.hardening.yml" \
		config --no-path-resolution
	[ "$status" -eq 0 ]
	[[ "$output" == *"cap_drop"* ]]
	[[ "$output" == *"docker.sock"* ]]
}

# ── compose_files never emits both overlays (R1-E scenario) ──────────────────

@test "compose_files: never emits both overlays simultaneously" {
	# Source the library stack to call compose_files directly.
	# shellcheck disable=SC1090
	source "$DRYDOCK_HOME/lib/common.sh"
	# shellcheck disable=SC1090
	source "$DRYDOCK_HOME/lib/paths.sh"
	# shellcheck disable=SC1090
	source "$DRYDOCK_HOME/lib/compose.sh"

	# Stub docker for GC/collision checks.
	local _stub="$BATS_TEST_TMPDIR/docker-stub-render-$$"
	cat >"$_stub" <<'STUB'
#!/usr/bin/env bash
if [ "${1:-}" = "ps" ]; then printf ''; fi
exit 0
STUB
	chmod +x "$_stub"
	export DOCKER="$_stub"

	local _home="$BATS_TEST_TMPDIR/render-no-both-$$"
	mkdir -p "$_home/.claude-container"
	touch "$_home/.claude-container.json"
	export HOME="$_home"

	local _proj="$BATS_TEST_TMPDIR/render-proj-$$"
	mkdir -p "$_proj"

	export MOUNTINFO_FILE=/dev/null
	unset DRYDOCK_DOOD DRYDOCK_CONTAIN

	local _output
	_output="$(compose_files "$_proj")"

	# Must contain exactly one of the two overlays, never both.
	local _dood_count=0 _contain_count=0
	[[ "$_output" == *"docker-compose.dood.yml"* ]] && _dood_count=1
	[[ "$_output" == *"docker-compose.contain.yml"* ]] && _contain_count=1
	[ $((_dood_count + _contain_count)) -eq 1 ]
}
